[package]
name = "macroni"
version = "1.0.0"
edition = "2024"
description = "Helpful macros to speed up development and reduce boilerplate"
license = "MIT"
repository = "https://github.com/topginga/macroni"

[dependencies]

[features]
default = []
rdev = []
rand = []
clearscreen = []
full = []
