[package]
name = "macroni"
version = "0.2.0"
edition = "2024"
description = "Helpful macros to speed up development and reduce boilerplate and imports."
license = "MIT"
repository = "https://github.com/topginga/macroni"

[dependencies]
